// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoLzUkqhTjKp85-fTcP_Yw_gY0vIkBJcQ',
    appId: '1:599685827780:web:5d46ccef540397fd8b0d91',
    messagingSenderId: '599685827780',
    projectId: 'myflix-135a5',
    authDomain: 'myflix-135a5.firebaseapp.com',
    storageBucket: 'myflix-135a5.firebasestorage.app',
    measurementId: 'G-NS844V6EFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjSLfIW1UwU4IHVPO6tN35SVsqhMMG_l8',
    appId: '1:599685827780:android:59ba1021e7202abc8b0d91',
    messagingSenderId: '599685827780',
    projectId: 'myflix-135a5',
    storageBucket: 'myflix-135a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTlQ_GIi2gCTmXyWm7BSumU_B2pSwVWZc',
    appId: '1:599685827780:ios:a86d5ecf9402705e8b0d91',
    messagingSenderId: '599685827780',
    projectId: 'myflix-135a5',
    storageBucket: 'myflix-135a5.firebasestorage.app',
    androidClientId: '599685827780-3mpi15ipuq5e7aimluolh7s421i0lkd0.apps.googleusercontent.com',
    iosClientId: '599685827780-h0jjqtpjff3k95f5a6q5uumg5rkhaddo.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTlQ_GIi2gCTmXyWm7BSumU_B2pSwVWZc',
    appId: '1:599685827780:ios:a86d5ecf9402705e8b0d91',
    messagingSenderId: '599685827780',
    projectId: 'myflix-135a5',
    storageBucket: 'myflix-135a5.firebasestorage.app',
    androidClientId: '599685827780-3mpi15ipuq5e7aimluolh7s421i0lkd0.apps.googleusercontent.com',
    iosClientId: '599685827780-h0jjqtpjff3k95f5a6q5uumg5rkhaddo.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoLzUkqhTjKp85-fTcP_Yw_gY0vIkBJcQ',
    appId: '1:599685827780:web:e386228883d84d858b0d91',
    messagingSenderId: '599685827780',
    projectId: 'myflix-135a5',
    authDomain: 'myflix-135a5.firebaseapp.com',
    storageBucket: 'myflix-135a5.firebasestorage.app',
    measurementId: 'G-8NG1B8F962',
  );
}
